### ISSUE TITLE
Black screen and freezing

### ISSUE THREAD

**Issue by E3RTT** [dtankdempse/thetvapp-m3u#13]
How do I fix these?

**Comment by dtankdempse** [comment]
Aside from clearing your cache, there isn't much you can do. It's likely that TheTVApp's server is currently experiencing high traffic or is overloaded.

**Comment by dtankdempse** [comment]
I'm not experiencing the issue you're describing. It might be worth clearing your cache and checking the amount of free storage on your device, as low storage can sometimes cause performance problems. What application are you using? You could also try loading the playlist in this browser-based player to see if the issue persists:

https://iptvnator.vercel.app/

If it works fine on a different device, then the problem likely lies on the client side with your device rather than with the playlist.

**Comment by gooru2u** [comment]
I was have similar issues. Tested website directly and worked flawlessly. After testing many apps on Apple TV I found one working very well. Couldn't get a good app to work with my Firestick that constantly buffers.

**Comment by E3RTT** [comment]
I've been using m3u iptv, I'm gonna try tivimate on my fire stick instead

**Comment by E3RTT** [comment]
So I found that the issues persist when I use the website also, if I change the resolution to 360p it works flawlessly, it's only when I use 720p.

**Comment by E3RTT** [comment]
Idk why it was happening but it's working fine now, you do great work man.
