### ISSUE TITLE
Tvapp Guide Pulling Pluto not tvapp

### ISSUE THREAD

**Issue by newf276** [dtankdempse/thetvapp-m3u#18]
First off thankyou for everything you do for the community.  Unfortunately the links for Tvapp Guide appears to be pulling PlutoTV Guide not Tvapp Guide, m3u seems fine. Not sure what the issue is.

thanks

**Comment by dtankdempse** [comment]
The EPG contains both Pluto TV and TheTVApp guide information since the script merges the two together. The guide data for TheTVApp is sourced from m3u4u, but their service is currently down. According to updates on their Discord channel, there's no estimated time of resolution. However, I have never seen it down for longer than a day."

Response:
`{"message":"Something is not right... Please, call one of our monkeys at support@m3u4u.com"}`

Once they come back up, the EPG data will start working again.

**Comment by newf276** [comment]
Thanks for the quick response, I figured it was something out of your control. Much appreciate the update, and yes m3u4u has had problems before, it is why I went with iptv editor for my personal account stuff.  Hope all is well, and thanks again for your time and effort, I am sure everyone appreciates all that you do for us.
