### ISSUE TITLE
Won't update

### ISSUE THREAD

**Issue by disableddabel** [dtankdempse/thetvapp-m3u#24]
Please

**Comment by dtankdempse** [comment]
This doesn't provide enough information. Please take the time to describe your issue in more detail rather than just three words, and I'll do my best to help.

**Comment by disableddabel** [comment]
It will only show channels it won't show sports events like NFL NHL PPV etc
![IMG_4131](https://github.com/user-attachments/assets/75aec409-956d-4266-946e-f9474ddbd34d)
![IMG_4130](https://github.com/user-attachments/assets/49cbbda8-9129-4515-9d52-389e262e537d)

**Comment by dtankdempse** [comment]
Oh, I see. Since TheTVApp no longer lists the actual streaming link when posting an event, the scraper keeps checking the page until the link is available. Once it’s posted, the event will be added to the playlist. The best thing to do is to update your playlist closer to the event time or later in the day, since the script can't add the event until a streaming link is found.

**Comment by dtankdempse** [comment]
Just because events are listed on the website doesn't mean they immediately have streaming links attached. Events are posted first, and the streaming links are added afterward. Also, keep in mind that once the links are available on their website, they won't be added to the playlist instantly. Instead, they get included during the next scraping cycle. There’s no need to worry—the events will be added once the scraper runs again.

The code is working properly, and there are no errors, so the events will be added.

**Comment by disableddabel** [comment]
Awesome, thanks for the info! And thank you for your patience and help

**Comment by dtankdempse** [comment]
> Awesome, thanks for the info! And thank you for your patience and help

 No problem.

**Comment by Jag4343** [comment]
EPG is working for thetvapp-m3u. It just says no information

**Comment by disableddabel** [comment]
Yeah same for me

**Comment by pitsi** [comment]
May I add that epgs do not work on the moj (moveonjoy) and ddy (daddylive) playlists too? Tested with the relevant playlists on kodi 21 and with removing any cache files before each test.
The epgs for ubi and su (streamedsu) work fine though.

And a big thank you for all the hard work you do!

**Comment by dtankdempse** [comment]
M3u4u, the service provider for most of the EPGs, is currently down. Once they are back up, the guide data will start working again. More information is available on their Discord: https://m3u4u.com/discord.
