### ISSUE TITLE
DOCKER: What are the names of the playlist and EPG files created by the container? 

### ISSUE THREAD

**Issue by zedstate** [dtankdempse/thetvapp-m3u#44]
Can you clarify the docker instructions to include the names of the playlist and EPG files?   Thanks!

**Comment by dtankdempse** [comment]
There are no files being created. When the server starts, it fetches and stores data files from this repository. When a playlist is requested, it adds a token to the playlist and serves the file for download.

**Comment by zedstate** [comment]
Ok - I assumed it was going to create the m3u and epg.xml files - which I would normally load into my IPTV client.   Not sure I know how to use this then.    Great work.

**Comment by dtankdempse** [comment]
Oh, I understand what you're asking now. To access the server, you'll need to use your computer's IP address along with the port number. The playlist and EPG details will be available at either:

 `http://IP:PORT` Or 'http://localhost:4124'


If you plan to use the playlist on other devices within your network, make sure to use your computer's actual IP address instead of localhost.

Here's how you can find your computer's IP address:

[On Windows](https://youtu.be/zOZWlTplrcA?si=nGXrHKU4sAQsy18e&t=18)
[On Linux](https://youtu.be/7c_V_3nWWbA)

**Comment by zedstate** [comment]
Correct.   For example I tried to add 'http://<my IP>:4124/thetvapp-m3u8' and several other variations '/thetvapp.m3u' or '/thetvapp.m3u8' and my IPTV client never found the files.    My assumption is that the docker just 'runs' your build script locally and servers up the files locally, so it's not hammered into oblivion.    I just don't know what those resulting *.m3u8 and *.xml files are called.    Hope this helps.

**Comment by dtankdempse** [comment]
Yeah, that's on me. I'll update the Read Me section. In the meantime, you can locate your computer's IP and load the URL like this: `http://IP_HERE:4124`, load it in your browser and you will see the playlist and epg. which will be:

Playlist:  `http://IP_HERE:4124/playlist`
EPG:  `http://IP_HERE:4124/epg`

**Comment by zedstate** [comment]
Thanks for your efforts and clarifying comments.   Successfully setup using /playlist and /epg.

**Comment by zedstate** [comment]
See comments above.   Pending updates to documentation.
